using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace CxShell.Services;

public sealed class LocalizationService : INotifyPropertyChanged
{
    public const string Chinese = "zh-CN";
    public const string English = "en-US";
    public static LocalizationService Shared { get; } = new();

    private static readonly Dictionary<string, string> EnglishTexts = new(StringComparer.Ordinal)
    {
        ["Toolbar.New"] = "New",
        ["Toolbar.NewTip"] = "Create a new session",
        ["Toolbar.Sessions"] = "Sessions",
        ["Toolbar.SessionsTip"] = "Open session manager",
        ["Toolbar.Connect"] = "Connect",
        ["Toolbar.ConnectTip"] = "Connect current session",
        ["Toolbar.Disconnect"] = "Disconnect",
        ["Toolbar.DisconnectTip"] = "Disconnect current session",
        ["Toolbar.SftpTip"] = "Show or hide SFTP file panel",
        ["Toolbar.Monitor"] = "Monitor",
        ["Toolbar.MonitorTip"] = "Show or hide server monitor",
        ["Toolbar.ThemeTip"] = "Switch light/dark theme",
        ["Toolbar.FullScreenTip"] = "Show current terminal in full screen",
        ["Toolbar.Arrange"] = "Arrange",
        ["Toolbar.ArrangeTip"] = "Arrange opened tabs",
        ["Toolbar.LanguageTip"] = "Switch display language",
        ["Toolbar.AddQuickSessionTip"] = "Add current session to quick bar",
        ["Arrange.Vertical"] = "Vertical",
        ["Arrange.Horizontal"] = "Horizontal",
        ["Arrange.Tile"] = "Tile",
        ["Arrange.Merge"] = "Merge all tab groups",
        ["Quick.Properties"] = "Properties",
        ["Quick.Delete"] = "Delete",
        ["TabMenu.Close"] = "Close",
        ["TabMenu.Properties"] = "Properties",
        ["TabMenu.AddQuick"] = "Add to quick bar",
        ["Welcome.SelectSession"] = "Click \"Sessions\" to choose a session, or click \"New\" to start",
        ["Welcome.BuiltWithAtomUI"] = "Built with AtomUI",
        ["FullScreen.EscBack"] = "ESC Back",
        ["Language.Chinese"] = "中文",
        ["Language.English"] = "English",
        ["SessionManager.Title"] = "Session Manager",
        ["SessionManager.New"] = "New",
        ["SessionManager.Copy"] = "Copy",
        ["SessionManager.Paste"] = "Paste",
        ["SessionManager.Properties"] = "Properties",
        ["SessionManager.Delete"] = "Delete",
        ["SessionManager.MoveUp"] = "Move Up",
        ["SessionManager.MoveDown"] = "Move Down",
        ["SessionManager.SearchPlaceholder"] = "Search name, host, or username",
        ["SessionManager.ColumnName"] = "Name",
        ["SessionManager.ColumnHost"] = "Host",
        ["SessionManager.ColumnUsername"] = "Username",
        ["SessionManager.ColumnProtocol"] = "Protocol",
        ["SessionManager.ColumnPort"] = "Port",
        ["SessionManager.Close"] = "Close",
        ["SessionManager.ShowOnStartup"] = "Show this dialog at startup",
        ["SessionEdit.TitleNew"] = "New Session",
        ["SessionEdit.TitleProperties"] = "Session Properties",
        ["SessionEdit.NavTitle"] = "Session Configuration",
        ["SessionEdit.NavSubtitle"] = "Connection settings",
        ["SessionEdit.Connection"] = "Connection",
        ["SessionEdit.LoginPrompt"] = "Login Prompts",
        ["SessionEdit.LoginScript"] = "Login Script",
        ["SessionEdit.Proxy"] = "Proxy",
        ["SessionEdit.KeepAlive"] = "Keep Alive",
        ["SessionEdit.Serial"] = "Serial",
        ["SessionEdit.Security"] = "Security",
        ["SessionEdit.Tunnel"] = "Tunneling",
        ["SessionEdit.Terminal"] = "Terminal",
        ["SessionEdit.Keyboard"] = "Keyboard",
        ["SessionEdit.VtMode"] = "VT Mode",
        ["SessionEdit.Advanced"] = "Advanced",
        ["SessionEdit.Appearance"] = "Appearance",
        ["SessionEdit.Window"] = "Window",
        ["SessionEdit.Highlight"] = "Highlight",
        ["SessionEdit.Transfer"] = "File Transfer",
        ["SessionEdit.Xymodem"] = "X/YMODEM File Transfer",
        ["SessionEdit.Zmodem"] = "ZMODEM File Transfer",
        ["SessionEdit.Logging"] = "Logging",
        ["SessionEdit.Bell"] = "Bell",
        ["SessionEdit.Tracing"] = "Tracing",
        ["SessionEdit.General"] = "General",
        ["SessionEdit.Name"] = "Name",
        ["SessionEdit.NamePlaceholder"] = "Example: Production Server",
        ["SessionEdit.Protocol"] = "Protocol",
        ["SessionEdit.ProtocolPlaceholder"] = "Select protocol",
        ["SessionEdit.Host"] = "Host",
        ["SessionEdit.HostPlaceholder"] = "192.168.1.100 or example.com",
        ["SessionEdit.Port"] = "Port",
        ["SessionEdit.UserAuth"] = "User Authentication",
        ["SessionEdit.Username"] = "Username",
        ["SessionEdit.AuthMethod"] = "Auth Method",
        ["SessionEdit.Password"] = "Password",
        ["SessionEdit.PrivateKey"] = "Private Key",
        ["SessionEdit.PromptPassword"] = "Leave empty to prompt for password when connecting.",
        ["SessionEdit.PasswordNotSaved"] = "Leave empty to prompt for password when connecting.",
        ["SessionEdit.PasswordSavedEncrypted"] = "Saved passwords are encrypted in the session file.",
        ["SessionEdit.PrivateKeyPath"] = "Private key path",
        ["SessionEdit.SshTunnelTitle"] = "SSH Tunneling",
        ["SessionEdit.VncSshTunnelTitle"] = "VNC SSH Tunneling",
        ["SessionEdit.UseVncSshTunnel"] = "Connect VNC through SSH tunnel",
        ["SessionEdit.VncSshTunnelDescription"] = "When selected, the host/port above is the VNC address reachable from the SSH server, for example 127.0.0.1:5901.",
        ["SessionEdit.UseRdpSshTunnel"] = "Connect RDP through SSH tunnel",
        ["SessionEdit.RdpSshTunnelDescription"] = "When selected, the host/port above is the RDP address reachable from the SSH server, for example 127.0.0.1:3389 or an internal Windows IP:3389. CxShell automatically creates a temporary local port.",
        ["SessionEdit.SshHost"] = "SSH Host",
        ["SessionEdit.SshPort"] = "SSH Port",
        ["SessionEdit.SshUsername"] = "SSH Username",
        ["SessionEdit.SshPassword"] = "SSH Password",
        ["SessionEdit.SshPrivateKey"] = "SSH Private Key",
        ["SessionEdit.Browse"] = "Browse",
        ["SessionEdit.Reconnect"] = "Reconnect",
        ["SessionEdit.AutoReconnect"] = "Automatically reconnect when connection closes unexpectedly",
        ["SessionEdit.Interval"] = "Interval",
        ["SessionEdit.Limit"] = "Limit",
        ["SessionEdit.Seconds"] = "sec",
        ["SessionEdit.Minutes"] = "min",
        ["SessionEdit.Save"] = "Save",
        ["SessionEdit.Cancel"] = "Cancel",
        ["SessionEdit.Placeholder"] = "This configuration page will be implemented in later steps.",
        ["Terminal.Connecting"] = "Connecting...",
        ["Terminal.Copy"] = "Copy",
        ["Terminal.Paste"] = "Paste",
        ["Sftp.Upload"] = "↑ Upload",
        ["Sftp.Download"] = "↓ Download",
        ["Sftp.Edit"] = "Edit",
        ["Sftp.NewDirectory"] = "+ Folder",
        ["Sftp.Name"] = "Name",
        ["Sftp.Size"] = "Size",
        ["Sftp.Modified"] = "Modified",
        ["Sftp.ConnectHint"] = "Open automatically after connecting an SSH session",
        ["Sftp.Loading"] = "Loading...",
        ["Common.Rename"] = "Rename",
        ["SessionEdit.LoginPrompt.TelnetDescription"] = "Specify username and password prompts so the TELNET login process can run automatically.",
        ["PasswordDialog.Title"] = "Enter Password - {0}",
        ["PasswordDialog.Placeholder"] = "Enter password",
        ["PasswordDialog.Ok"] = "OK",
        ["PasswordDialog.Cancel"] = "Cancel",
        ["PasswordDialog.User"] = "User: {0}@{1}:{2}",
        ["Monitor.StatusRunning"] = "Monitoring",
        ["Monitor.StatusStopped"] = "Stopped",
        ["Monitor.MemoryUsed"] = "Used",
        ["Monitor.MemoryCached"] = "Cached",
        ["Monitor.MemoryFree"] = "Free",
        ["Monitor.MemoryUsedFormat"] = "Used {0}",
        ["Monitor.MemoryCachedFormat"] = "Cached {0}",
        ["Monitor.MemoryFreeFormat"] = "Free {0}",
        ["Monitor.MemoryTotalFormat"] = "Total {0}",
        ["Monitor.CpuTotal"] = "Total",
        ["Monitor.CpuCore"] = "Core {0}",
        ["Monitor.NotConnected"] = "Not connected",
        ["Monitor.ConnectionFailed"] = "Monitor connection failed: {0}",
        ["Monitor.CollectFailed"] = "Collection failed: {0}",
        ["Monitor.CommandFailed"] = "Command timed out or failed: {0}",
        ["Session.CopySuffix"] = "{0} - Copy",
        ["Validation.SessionNameRequired"] = "Enter a session name.",
        ["Validation.HostRequired"] = "Enter a host address.",
        ["Validation.PortRequired"] = "Enter a port number.",
        ["Validation.PortRange"] = "Port must be an integer between 1 and 65535.",
        ["Validation.SerialPortRequired"] = "Enter a serial port name.",
        ["Option.None"] = "<None>",
        ["Option.DefaultLanguage"] = "Default language",
        ["Option.Default"] = "Default",
        ["Option.UserCustom"] = "User custom",
        ["Option.Normal"] = "Normal",
        ["Option.Application"] = "Application",
        ["Option.ForceNormal"] = "Force normal",
        ["Option.Draft"] = "Draft",
        ["Option.Proof"] = "Proof",
        ["Option.NonAntiAliased"] = "Non anti-aliased",
        ["Option.AntiAliased"] = "Anti-aliased",
        ["Option.NaturalClearType"] = "Natural ClearType",
        ["Option.BoldColor"] = "Use bold color",
        ["Option.BoldFont"] = "Use bold font",
        ["Option.BoldColorAndFont"] = "Use bold color and font",
        ["Option.Block"] = "Block",
        ["Option.Vertical"] = "Vertical bar",
        ["Option.Underline"] = "Underline",
        ["Option.Center"] = "Center",
        ["Option.Tile"] = "Tile",
        ["Option.Stretch"] = "Stretch",
        ["Option.TopLeft"] = "Top left",
        ["Option.TopRight"] = "Top right",
        ["Option.BottomLeft"] = "Bottom left",
        ["Option.BottomRight"] = "Bottom right",
        ["Option.Ssh2ThenSsh1"] = "SSH2, SSH1 (choose SSH2 if the server supports both)",
        ["Option.Ssh1ThenSsh2"] = "SSH1, SSH2 (choose SSH1 if the server supports both)",
        ["Option.Ssh2Only"] = "SSH2 only (do not use SSH1)",
        ["Option.Ssh1Only"] = "SSH1 only (do not use SSH2)",
        ["Option.Odd"] = "Odd",
        ["Option.Even"] = "Even",
        ["Option.Mark"] = "Mark",
        ["Option.Space"] = "Space",
        ["Option.NotUsed"] = "Not used",
        ["Option.SmartSizing"] = "Use smart sizing",
        ["Option.SmartReconnect"] = "Use smart reconnect",
        ["Option.LegacyReconnect"] = "Use legacy reconnect",
        ["Option.Auto"] = "Auto",
    };

    private static readonly Dictionary<string, string> ChineseTexts = new(StringComparer.Ordinal)
    {
        ["Toolbar.New"] = "新建",
        ["Toolbar.NewTip"] = "新建会话",
        ["Toolbar.Sessions"] = "会话",
        ["Toolbar.SessionsTip"] = "打开会话管理器",
        ["Toolbar.Connect"] = "连接",
        ["Toolbar.ConnectTip"] = "连接当前会话",
        ["Toolbar.Disconnect"] = "断开",
        ["Toolbar.DisconnectTip"] = "断开当前会话",
        ["Toolbar.SftpTip"] = "显示或隐藏 SFTP 文件面板",
        ["Toolbar.Monitor"] = "监控",
        ["Toolbar.MonitorTip"] = "显示或隐藏服务器监控",
        ["Toolbar.ThemeTip"] = "切换亮色/暗色主题",
        ["Toolbar.FullScreenTip"] = "全屏显示当前终端",
        ["Toolbar.Arrange"] = "排列",
        ["Toolbar.ArrangeTip"] = "排列当前打开的选项卡",
        ["Toolbar.LanguageTip"] = "切换显示语言",
        ["Toolbar.AddQuickSessionTip"] = "将当前会话加入快捷标签栏",
        ["Arrange.Vertical"] = "垂直排列(V)",
        ["Arrange.Horizontal"] = "水平排列(H)",
        ["Arrange.Tile"] = "瓷砖排列(T)",
        ["Arrange.Merge"] = "合并所有选项卡组(M)",
        ["Quick.Properties"] = "属性",
        ["Quick.Delete"] = "删除",
        ["Welcome.SelectSession"] = "点击「会话」选择会话并连接，或点击「新建」开始",
        ["Welcome.BuiltWithAtomUI"] = "基于 AtomUI 开发",
        ["FullScreen.EscBack"] = "ESC 返回",
        ["Language.Chinese"] = "中文",
        ["Language.English"] = "English",
        ["SessionManager.Title"] = "会话管理器",
        ["SessionManager.New"] = "新建",
        ["SessionManager.Copy"] = "复制",
        ["SessionManager.Paste"] = "粘贴",
        ["SessionManager.Properties"] = "属性",
        ["SessionManager.Delete"] = "删除",
        ["SessionManager.MoveUp"] = "上移",
        ["SessionManager.MoveDown"] = "下移",
        ["SessionManager.SearchPlaceholder"] = "搜索名称、主机、用户名",
        ["SessionManager.ColumnName"] = "名称",
        ["SessionManager.ColumnHost"] = "主机",
        ["SessionManager.ColumnUsername"] = "用户名",
        ["SessionManager.ColumnProtocol"] = "协议",
        ["SessionManager.ColumnPort"] = "端口",
        ["SessionManager.Close"] = "关闭",
        ["SessionManager.ShowOnStartup"] = "启动时显示此对话框",
        ["SessionEdit.TitleNew"] = "新建会话",
        ["SessionEdit.TitleProperties"] = "会话属性",
        ["SessionEdit.NavTitle"] = "会话配置",
        ["SessionEdit.NavSubtitle"] = "连接相关设置",
        ["SessionEdit.Connection"] = "连接",
        ["SessionEdit.LoginPrompt"] = "登录提示符",
        ["SessionEdit.LoginScript"] = "登录脚本",
        ["SessionEdit.Proxy"] = "代理",
        ["SessionEdit.KeepAlive"] = "保持活动",
        ["SessionEdit.Serial"] = "串口",
        ["SessionEdit.Security"] = "安全性",
        ["SessionEdit.Tunnel"] = "隧道",
        ["SessionEdit.Terminal"] = "终端",
        ["SessionEdit.Keyboard"] = "键盘",
        ["SessionEdit.VtMode"] = "VT 模式",
        ["SessionEdit.Advanced"] = "高级",
        ["SessionEdit.Appearance"] = "外观",
        ["SessionEdit.Window"] = "窗口",
        ["SessionEdit.Highlight"] = "突出",
        ["SessionEdit.Transfer"] = "文件传输",
        ["SessionEdit.Xymodem"] = "X/YMODEM 文件传输",
        ["SessionEdit.Zmodem"] = "ZMODEM 文件传输",
        ["SessionEdit.Logging"] = "日志记录",
        ["SessionEdit.Bell"] = "响铃",
        ["SessionEdit.Tracing"] = "跟踪",
        ["SessionEdit.General"] = "常规",
        ["SessionEdit.Name"] = "名称",
        ["SessionEdit.NamePlaceholder"] = "例如：生产服务器",
        ["SessionEdit.Protocol"] = "协议",
        ["SessionEdit.ProtocolPlaceholder"] = "请选择协议",
        ["SessionEdit.Host"] = "主机",
        ["SessionEdit.HostPlaceholder"] = "192.168.1.100 或 example.com",
        ["SessionEdit.Port"] = "端口",
        ["SessionEdit.UserAuth"] = "用户身份验证",
        ["SessionEdit.Username"] = "用户名",
        ["SessionEdit.AuthMethod"] = "认证方法",
        ["SessionEdit.Password"] = "密码",
        ["SessionEdit.PrivateKey"] = "私钥",
        ["SessionEdit.PromptPassword"] = "留空则连接时提示输入密码。",
        ["SessionEdit.PasswordNotSaved"] = "留空则连接时提示输入密码。",
        ["SessionEdit.PasswordSavedEncrypted"] = "保存后的密码会加密存储到会话文件。",
        ["SessionEdit.PrivateKeyPath"] = "私钥路径",
        ["SessionEdit.SshTunnelTitle"] = "SSH 隧道",
        ["SessionEdit.VncSshTunnelTitle"] = "VNC SSH 隧道",
        ["SessionEdit.UseVncSshTunnel"] = "通过 SSH 隧道连接 VNC",
        ["SessionEdit.VncSshTunnelDescription"] = "勾选后，上方主机/端口表示 SSH 服务器内部可访问的 VNC 地址，例如 127.0.0.1:5901。",
        ["SessionEdit.UseRdpSshTunnel"] = "通过 SSH 隧道连接 RDP",
        ["SessionEdit.RdpSshTunnelDescription"] = "勾选后，上方主机/端口表示 SSH 服务器内部可访问的 RDP 地址，例如 127.0.0.1:3389 或内网 Windows IP:3389。CxShell 会自动创建本地临时端口。",
        ["SessionEdit.SshHost"] = "SSH 主机",
        ["SessionEdit.SshPort"] = "SSH 端口",
        ["SessionEdit.SshUsername"] = "SSH 用户",
        ["SessionEdit.SshPassword"] = "SSH 密码",
        ["SessionEdit.SshPrivateKey"] = "SSH 私钥",
        ["SessionEdit.Browse"] = "浏览",
        ["SessionEdit.Reconnect"] = "重新连接",
        ["SessionEdit.AutoReconnect"] = "连接异常关闭时自动重新连接",
        ["SessionEdit.Interval"] = "间隔",
        ["SessionEdit.Limit"] = "限制",
        ["SessionEdit.Seconds"] = "秒",
        ["SessionEdit.Minutes"] = "分钟",
        ["SessionEdit.Save"] = "保存",
        ["SessionEdit.Cancel"] = "取消",
        ["SessionEdit.Placeholder"] = "此配置页将在后续步骤中实现。",
        ["Terminal.Connecting"] = "正在连接...",
        ["Terminal.Copy"] = "复制",
        ["Terminal.Paste"] = "粘贴",
        ["Sftp.Upload"] = "↑ 上传",
        ["Sftp.Download"] = "↓ 下载",
        ["Sftp.Edit"] = "编辑",
        ["Sftp.NewDirectory"] = "+ 目录",
        ["Sftp.Name"] = "名称",
        ["Sftp.Size"] = "大小",
        ["Sftp.Modified"] = "修改时间",
        ["Sftp.ConnectHint"] = "连接 SSH 会话后自动打开",
        ["Sftp.Loading"] = "正在加载...",
        ["Common.Rename"] = "重命名",
        ["SessionEdit.LoginPrompt.TelnetDescription"] = "请指定用户名和密码提示，以便 TELNET 登录过程可自动运行。",
        ["PasswordDialog.Title"] = "输入密码 - {0}",
        ["PasswordDialog.Placeholder"] = "请输入密码",
        ["PasswordDialog.Ok"] = "确定",
        ["PasswordDialog.Cancel"] = "取消",
        ["PasswordDialog.User"] = "用户: {0}@{1}:{2}",
        ["Monitor.StatusRunning"] = "监控中",
        ["Monitor.StatusStopped"] = "已停止",
        ["Monitor.MemoryUsed"] = "已用",
        ["Monitor.MemoryCached"] = "缓存",
        ["Monitor.MemoryFree"] = "空闲",
        ["Monitor.MemoryUsedFormat"] = "已用 {0}",
        ["Monitor.MemoryCachedFormat"] = "缓存 {0}",
        ["Monitor.MemoryFreeFormat"] = "空闲 {0}",
        ["Monitor.MemoryTotalFormat"] = "共 {0}",
        ["Monitor.CpuTotal"] = "总计",
        ["Monitor.CpuCore"] = "核心 {0}",
        ["Monitor.NotConnected"] = "未连接",
        ["Monitor.ConnectionFailed"] = "监控连接失败: {0}",
        ["Monitor.CollectFailed"] = "采集失败: {0}",
        ["Monitor.CommandFailed"] = "命令执行超时或失败: {0}",
        ["Session.CopySuffix"] = "{0} - 副本",
        ["Validation.SessionNameRequired"] = "请输入会话名称。",
        ["Validation.HostRequired"] = "请输入主机地址。",
        ["Validation.PortRequired"] = "请输入端口号。",
        ["Validation.PortRange"] = "端口必须是 1 到 65535 之间的整数。",
        ["Validation.SerialPortRequired"] = "请输入串口名称。",
        ["Option.None"] = "<无>",
        ["Option.DefaultLanguage"] = "默认语言",
        ["Option.Default"] = "默认",
        ["Option.UserCustom"] = "用户自定义",
        ["Option.Normal"] = "普通",
        ["Option.Application"] = "应用程序",
        ["Option.ForceNormal"] = "强制普通",
        ["Option.Draft"] = "草稿",
        ["Option.Proof"] = "预览",
        ["Option.NonAntiAliased"] = "无抗锯齿",
        ["Option.AntiAliased"] = "抗锯齿",
        ["Option.NaturalClearType"] = "自然 ClearType",
        ["Option.BoldColor"] = "使用大胆的色彩",
        ["Option.BoldFont"] = "使用粗体",
        ["Option.BoldColorAndFont"] = "使用大胆的颜色和字体",
        ["Option.Block"] = "块",
        ["Option.Vertical"] = "竖线",
        ["Option.Underline"] = "下划线",
        ["Option.Center"] = "中央",
        ["Option.Tile"] = "瓦",
        ["Option.Stretch"] = "伸展",
        ["Option.TopLeft"] = "左上方",
        ["Option.TopRight"] = "右上",
        ["Option.BottomLeft"] = "左下方",
        ["Option.BottomRight"] = "右下",
        ["Option.Ssh2ThenSsh1"] = "SSH2, SSH1 (如果服务器同时支持，则选择SSH2)",
        ["Option.Ssh1ThenSsh2"] = "SSH1, SSH2 (如果服务器同时支持，则选择SSH1)",
        ["Option.Ssh2Only"] = "仅SSH2(不使用SSH1)",
        ["Option.Ssh1Only"] = "仅SSH1(不使用SSH2)",
        ["Option.Odd"] = "奇",
        ["Option.Even"] = "偶",
        ["Option.Mark"] = "标记",
        ["Option.Space"] = "空格",
        ["Option.NotUsed"] = "不使用",
        ["Option.SmartSizing"] = "使用智能调整大小",
        ["Option.SmartReconnect"] = "使用智能重新连接",
        ["Option.LegacyReconnect"] = "使用旧版重新连接",
        ["Option.Auto"] = "自动",
    };
    static LocalizationService()
    {
        AddGeneratedTexts(EnglishTexts, ChineseTexts);
        AddDialogTexts(EnglishTexts, ChineseTexts);
        EnglishTexts["TabMenu.Close"] = "Close";
        EnglishTexts["TabMenu.Properties"] = "Properties";
        EnglishTexts["TabMenu.AddQuick"] = "Add to quick bar";
        ChineseTexts["TabMenu.Close"] = "\u5173\u95ed";
        ChineseTexts["TabMenu.Properties"] = "\u5c5e\u6027";
        ChineseTexts["TabMenu.AddQuick"] = "\u6dfb\u52a0\u5230\u6807\u7b7e";
    }

    private static void AddDialogTexts(Dictionary<string, string> english, Dictionary<string, string> chinese)
    {
        english["Common.Ok"] = "OK";
        english["Common.Cancel"] = "Cancel";
        english["Common.Delete"] = "Delete";
        english["Common.Close"] = "Close";
        english["Common.Add"] = "Add";
        english["Common.Edit"] = "Edit";
        english["Common.MoveUp"] = "Move Up";
        english["Common.MoveDown"] = "Move Down";
        english["Common.SelectAll"] = "Select All";
        english["Common.Clear"] = "Clear";
        english["Dialog.FilePicker.SftpLocalStart"] = "Select local SFTP start folder";
        english["Dialog.FilePicker.LoginScript"] = "Select login script file";
        english["Dialog.FilePicker.BackgroundImage"] = "Select background image";
        english["Dialog.FilePicker.ImageFiles"] = "Image files";
        english["Dialog.FilePicker.KeyboardMapping"] = "Select keyboard mapping file";
        english["Dialog.FilePicker.DownloadDirectory"] = "Select download directory";
        english["Dialog.FilePicker.UploadDirectory"] = "Select upload directory";
        english["Dialog.FilePicker.LogFile"] = "Select log file";
        english["Dialog.FilePicker.SoundFile"] = "Select sound file";
        english["Dialog.FilePicker.SoundFiles"] = "Sound files";
        english["Dialog.FilePicker.SessionFile"] = "Select session file";
        english["Dialog.QuickCommandSet.Title"] = "Select Quick Command Set";
        english["Dialog.QuickCommandSet.AllCommands"] = "All Commands";
        english["Dialog.Highlight.Title"] = "Highlight Sets";
        english["Dialog.Highlight.Set"] = "Set";
        english["Dialog.Highlight.Keyword"] = "Keyword";
        english["Dialog.Highlight.Preview"] = "Preview";
        english["Dialog.Highlight.Description"] = "Description";
        english["Dialog.Highlight.NewSetName"] = "New Highlight Set {0}";
        english["Dialog.Highlight.SaveAs"] = "Save As";
        english["Dialog.Highlight.SetCurrent"] = "Set Current";
        english["Dialog.Highlight.DeleteSetTitle"] = "Delete Highlight Set";
        english["Dialog.Highlight.DeleteSetMessage"] = "Delete \"{0}\"?";
        english["Dialog.Highlight.RuleTitle"] = "Keyword";
        english["Dialog.Highlight.CaseSensitive"] = "Case sensitive (C)";
        english["Dialog.Highlight.Regex"] = "Regular expression (R)";
        english["Dialog.Highlight.TerminalColor"] = "Terminal color (M)";
        english["Dialog.Highlight.Bold"] = "Bold (B)";
        english["Dialog.Highlight.Italic"] = "Italic (I)";
        english["Dialog.Highlight.Underline"] = "Underline (U)";
        english["Dialog.Highlight.Strikethrough"] = "Strikethrough (S)";
        english["Dialog.Highlight.KeywordLabel"] = "Keyword to highlight (K):";
        english["Dialog.Highlight.DescriptionLabel"] = "Description (D):";
        english["Dialog.Highlight.TextColor"] = "Text color (T):";
        english["Dialog.Highlight.BackgroundColor"] = "Background color (G):";
        english["Dialog.Highlight.View"] = "View";
        english["Dialog.Proxy.ListTitle"] = "Proxy List";
        english["Dialog.Proxy.SettingsTitle"] = "Proxy Server Settings";
        english["Dialog.Proxy.ServerTitle"] = "Proxy Server";
        english["Dialog.Proxy.Name"] = "Name";
        english["Dialog.Proxy.Type"] = "Type";
        english["Dialog.Proxy.Host"] = "Host";
        english["Dialog.Proxy.Port"] = "Port";
        english["Dialog.Proxy.Username"] = "Username";
        english["Dialog.Proxy.Password"] = "Password";
        english["Dialog.Proxy.NextProxy"] = "Next Proxy";
        english["Dialog.Proxy.SessionFile"] = "Session file (S)";
        english["Dialog.Proxy.Browse"] = "Browse (B)...";
        english["Dialog.Proxy.DeleteTitle"] = "Delete Proxy";
        english["Dialog.Proxy.DeleteMessage"] = "Delete proxy \"{0}\"?";
        english["Dialog.Proxy.NameRequired"] = "Enter a proxy name.";
        english["Dialog.Proxy.HostRequired"] = "Enter a proxy server host.";
        english["Dialog.Proxy.PortRange"] = "Port must be an integer between 1 and 65535.";
        english["Dialog.LoginScriptRule.Title"] = "Wait and Send Rule";
        english["Dialog.LoginScriptRule.HideText"] = "Hide text (H)";
        english["Dialog.LoginScriptRule.WaitPrompt"] = "Enter the string to wait for.";
        english["Dialog.LoginScriptRule.WaitLabel"] = "Wait (E):";
        english["Dialog.LoginScriptRule.SendPrompt"] = "Enter the text to send when the wait string is received.";
        english["Dialog.LoginScriptRule.SendLabel"] = "Send (S):";
        english["Dialog.TunnelRule.Title"] = "Tunneling Rule";
        english["Dialog.TunnelRule.Local"] = "Local (Outgoing)";
        english["Dialog.TunnelRule.Remote"] = "Remote (Incoming)";
        english["Dialog.TunnelRule.AcceptLocalOnly"] = "Accept local connections only (A)";
        english["Dialog.TunnelRule.TypeDirection"] = "Type (Direction) (T):";
        english["Dialog.TunnelRule.SourceHost"] = "Source host (S):";
        english["Dialog.TunnelRule.ListenPort"] = "Listen port (L):";
        english["Dialog.TunnelRule.TargetHost"] = "Target host (H):";
        english["Dialog.TunnelRule.TargetPort"] = "Target port (P):";
        english["Dialog.TunnelRule.Description"] = "Description (D):";
        english["Dialog.TunnelRule.ListenPortRequired"] = "Select a listen port.";
        english["Dialog.TunnelRule.TargetPortRequired"] = "Select a target port.";
        english["Dialog.Algorithm.CipherTitle"] = "Edit Cipher Algorithms";
        english["Dialog.Algorithm.MacTitle"] = "Edit MAC Algorithms";
        english["Dialog.Algorithm.KexTitle"] = "Edit Key Exchange Algorithms";
        english["Dialog.ServicePort.Placeholder"] = "Search service or port";
        english["Dialog.SessionDelete.Title"] = "Confirm Delete";
        english["Dialog.SessionDelete.Message"] = "Delete session \"{0}\"?";

        chinese["Common.Ok"] = "\u786e\u5b9a";
        chinese["Common.Cancel"] = "\u53d6\u6d88";
        chinese["Common.Delete"] = "\u5220\u9664";
        chinese["Common.Close"] = "\u5173\u95ed";
        chinese["Common.Add"] = "\u6dfb\u52a0";
        chinese["Common.Edit"] = "\u7f16\u8f91";
        chinese["Common.MoveUp"] = "\u4e0a\u79fb";
        chinese["Common.MoveDown"] = "\u4e0b\u79fb";
        chinese["Common.SelectAll"] = "\u5168\u9009";
        chinese["Common.Clear"] = "\u6e05\u7a7a";
        chinese["Dialog.FilePicker.SftpLocalStart"] = "\u9009\u62e9\u672c\u5730 SFTP \u8d77\u59cb\u6587\u4ef6\u5939";
        chinese["Dialog.FilePicker.LoginScript"] = "\u9009\u62e9\u767b\u5f55\u811a\u672c\u6587\u4ef6";
        chinese["Dialog.FilePicker.BackgroundImage"] = "\u9009\u62e9\u80cc\u666f\u56fe\u7247";
        chinese["Dialog.FilePicker.ImageFiles"] = "\u56fe\u7247\u6587\u4ef6";
        chinese["Dialog.FilePicker.KeyboardMapping"] = "\u9009\u62e9\u952e\u76d8\u6620\u5c04\u6587\u4ef6";
        chinese["Dialog.FilePicker.DownloadDirectory"] = "\u9009\u62e9\u4e0b\u8f7d\u8def\u5f84";
        chinese["Dialog.FilePicker.UploadDirectory"] = "\u9009\u62e9\u52a0\u8f7d\u8def\u5f84";
        chinese["Dialog.FilePicker.LogFile"] = "\u9009\u62e9\u65e5\u5fd7\u6587\u4ef6";
        chinese["Dialog.FilePicker.SoundFile"] = "\u9009\u62e9\u58f0\u97f3\u6587\u4ef6";
        chinese["Dialog.FilePicker.SoundFiles"] = "\u58f0\u97f3\u6587\u4ef6";
        chinese["Dialog.FilePicker.SessionFile"] = "\u9009\u62e9\u4f1a\u8bdd\u6587\u4ef6";
        chinese["Dialog.QuickCommandSet.Title"] = "\u9009\u62e9\u5feb\u901f\u547d\u4ee4\u96c6";
        chinese["Dialog.QuickCommandSet.AllCommands"] = "\u6240\u6709\u547d\u4ee4";
        chinese["Dialog.Highlight.Title"] = "\u7a81\u51fa\u663e\u793a\u96c6";
        chinese["Dialog.Highlight.Set"] = "\u96c6";
        chinese["Dialog.Highlight.Keyword"] = "\u5173\u952e\u5b57";
        chinese["Dialog.Highlight.Preview"] = "\u9884\u89c8";
        chinese["Dialog.Highlight.Description"] = "\u8bf4\u660e";
        chinese["Dialog.Highlight.NewSetName"] = "\u65b0\u7684\u7a81\u51fa\u663e\u793a\u96c6 {0}";
        chinese["Dialog.Highlight.SaveAs"] = "\u53e6\u5b58\u4e3a";
        chinese["Dialog.Highlight.SetCurrent"] = "\u8bbe\u7f6e\u4e3a\u5f53\u524d\u7ec4";
        chinese["Dialog.Highlight.DeleteSetTitle"] = "\u5220\u9664\u7a81\u51fa\u663e\u793a\u96c6";
        chinese["Dialog.Highlight.DeleteSetMessage"] = "\u786e\u5b9a\u5220\u9664\u201c{0}\u201d\u5417\uff1f";
        chinese["Dialog.Highlight.RuleTitle"] = "\u5173\u952e\u5b57";
        chinese["Dialog.Highlight.CaseSensitive"] = "\u533a\u5206\u5927\u5c0f\u5199(C)";
        chinese["Dialog.Highlight.Regex"] = "\u6b63\u5219\u8868\u8fbe\u5f0f(R)";
        chinese["Dialog.Highlight.TerminalColor"] = "\u7ec8\u7aef\u989c\u8272(M)";
        chinese["Dialog.Highlight.Bold"] = "\u7c97\u4f53(B)";
        chinese["Dialog.Highlight.Italic"] = "\u659c\u4f53(I)";
        chinese["Dialog.Highlight.Underline"] = "\u4e0b\u5212\u7ebf(U)";
        chinese["Dialog.Highlight.Strikethrough"] = "\u5220\u9664\u7ebf(S)";
        chinese["Dialog.Highlight.KeywordLabel"] = "\u8981\u5f3a\u8c03\u7684\u5173\u952e\u5b57(K):";
        chinese["Dialog.Highlight.DescriptionLabel"] = "\u8bf4\u660e(D):";
        chinese["Dialog.Highlight.TextColor"] = "\u6587\u672c\u989c\u8272(T):";
        chinese["Dialog.Highlight.BackgroundColor"] = "\u80cc\u666f\u989c\u8272(G):";
        chinese["Dialog.Highlight.View"] = "\u67e5\u770b";
        chinese["Dialog.Proxy.ListTitle"] = "\u5217\u8868\u4ee3\u7406";
        chinese["Dialog.Proxy.SettingsTitle"] = "\u4ee3\u7406\u670d\u52a1\u5668\u8bbe\u7f6e";
        chinese["Dialog.Proxy.ServerTitle"] = "\u4ee3\u7406\u670d\u52a1\u5668";
        chinese["Dialog.Proxy.Name"] = "\u540d\u79f0";
        chinese["Dialog.Proxy.Type"] = "\u7c7b\u578b";
        chinese["Dialog.Proxy.Host"] = "\u4e3b\u673a";
        chinese["Dialog.Proxy.Port"] = "\u7aef\u53e3";
        chinese["Dialog.Proxy.Username"] = "\u7528\u6237\u540d";
        chinese["Dialog.Proxy.Password"] = "\u5bc6\u7801";
        chinese["Dialog.Proxy.NextProxy"] = "\u4e0b\u4e00\u4ee3\u7406";
        chinese["Dialog.Proxy.SessionFile"] = "\u4f1a\u8bdd\u6587\u4ef6(S)";
        chinese["Dialog.Proxy.Browse"] = "\u6d4f\u89c8(B)...";
        chinese["Dialog.Proxy.DeleteTitle"] = "\u5220\u9664\u4ee3\u7406";
        chinese["Dialog.Proxy.DeleteMessage"] = "\u786e\u5b9a\u5220\u9664\u4ee3\u7406\u201c{0}\u201d\u5417\uff1f";
        chinese["Dialog.Proxy.NameRequired"] = "\u8bf7\u8f93\u5165\u4ee3\u7406\u540d\u79f0\u3002";
        chinese["Dialog.Proxy.HostRequired"] = "\u8bf7\u8f93\u5165\u4ee3\u7406\u670d\u52a1\u5668\u4e3b\u673a\u3002";
        chinese["Dialog.Proxy.PortRange"] = "\u7aef\u53e3\u5fc5\u987b\u662f 1 \u5230 65535 \u4e4b\u95f4\u7684\u6574\u6570\u3002";
        chinese["Dialog.LoginScriptRule.Title"] = "\u7b49\u5f85\u5e76\u53d1\u9001\u89c4\u5219";
        chinese["Dialog.LoginScriptRule.HideText"] = "\u9690\u85cf\u6587\u672c(H)";
        chinese["Dialog.LoginScriptRule.WaitPrompt"] = "\u8bf7\u8f93\u5165\u7b49\u5f85\u7684\u5b57\u7b26\u4e32\u3002";
        chinese["Dialog.LoginScriptRule.WaitLabel"] = "\u7b49\u5f85(E):";
        chinese["Dialog.LoginScriptRule.SendPrompt"] = "\u63a5\u6536\u7b49\u5f85\u5b57\u7b26\u4e32\u65f6\u8bf7\u8f93\u5165\u53d1\u9001\u7684\u6587\u672c\u3002";
        chinese["Dialog.LoginScriptRule.SendLabel"] = "\u53d1\u9001(S):";
        chinese["Dialog.TunnelRule.Title"] = "\u96a7\u9053\u89c4\u5219";
        chinese["Dialog.TunnelRule.Local"] = "\u672c\u5730\uff08\u62e8\u51fa\uff09";
        chinese["Dialog.TunnelRule.Remote"] = "\u8fdc\u7a0b\uff08\u4f20\u5165\uff09";
        chinese["Dialog.TunnelRule.AcceptLocalOnly"] = "\u4ec5\u63a5\u53d7\u672c\u5730\u8fde\u63a5(A)";
        chinese["Dialog.TunnelRule.TypeDirection"] = "\u7c7b\u578b (\u65b9\u5411)(T):";
        chinese["Dialog.TunnelRule.SourceHost"] = "\u6e90\u4e3b\u673a(S):";
        chinese["Dialog.TunnelRule.ListenPort"] = "\u4fa6\u542c\u7aef\u53e3(L):";
        chinese["Dialog.TunnelRule.TargetHost"] = "\u76ee\u6807\u4e3b\u673a(H):";
        chinese["Dialog.TunnelRule.TargetPort"] = "\u76ee\u6807\u7aef\u53e3(P):";
        chinese["Dialog.TunnelRule.Description"] = "\u8bf4\u660e(D):";
        chinese["Dialog.TunnelRule.ListenPortRequired"] = "\u8bf7\u9009\u62e9\u4fa6\u542c\u7aef\u53e3\u3002";
        chinese["Dialog.TunnelRule.TargetPortRequired"] = "\u8bf7\u9009\u62e9\u76ee\u6807\u7aef\u53e3\u3002";
        chinese["Dialog.Algorithm.CipherTitle"] = "\u7f16\u8f91\u52a0\u5bc6\u7b97\u6cd5";
        chinese["Dialog.Algorithm.MacTitle"] = "\u7f16\u8f91 MAC \u7b97\u6cd5";
        chinese["Dialog.Algorithm.KexTitle"] = "\u7f16\u8f91\u5bc6\u94a5\u4ea4\u6362\u7b97\u6cd5";
        chinese["Dialog.ServicePort.Placeholder"] = "\u641c\u7d22\u670d\u52a1\u6216\u7aef\u53e3";
        chinese["Dialog.SessionDelete.Title"] = "\u786e\u8ba4\u5220\u9664";
        chinese["Dialog.SessionDelete.Message"] = "\u786e\u5b9a\u8981\u5220\u9664\u4f1a\u8bdd\u201c{0}\u201d\u5417\uff1f";
    }

    private static void AddGeneratedTexts(Dictionary<string, string> english, Dictionary<string, string> chinese)
    {
        english["UiText.001"] = "Server Monitor";
        english["UiText.002"] = "Memory";
        english["UiText.003"] = "Network";
        english["UiText.004"] = "↓ Download";
        english["UiText.005"] = "↑ Upload";
        english["UiText.006"] = "Disk";
        english["UiText.007"] = "Disk I/O";
        english["UiText.008"] = "Read";
        english["UiText.009"] = "Write";
        english["UiText.010"] = "Keep Alive";
        english["UiText.011"] = "Send keep-alive messages while the session is connected (S)";
        english["UiText.012"] = "Interval (I):";
        english["UiText.013"] = "Send string when network is idle (R)";
        english["UiText.014"] = "Interval (E):";
        english["UiText.015"] = "String (G):";
        english["UiText.016"] = "Send TCP keep-alive packets while network is idle (T)";
        english["UiText.017"] = "Username prompt";
        english["UiText.018"] = "Password prompt";
        english["UiText.019"] = "Specify the password prompt so the RLOGIN login process can run automatically.";
        english["UiText.020"] = "After successfully logging in to the server, commands added with wait-and-send rules can be executed, or a second automatic login can be used.";
        english["UiText.021"] = "Execute the following wait-and-send rules (X).";
        english["UiText.022"] = "Add (A)...";
        english["UiText.023"] = "Edit (E)...";
        english["UiText.024"] = "Delete (R)";
        english["UiText.025"] = "Move Up (U)";
        english["UiText.026"] = "Move Down (D)";
        english["UiText.027"] = "Run script when connecting the session (S).";
        english["UiText.028"] = "Parameters (P):";
        english["UiText.029"] = "Remote Command";
        english["UiText.030"] = "Specify the remote command to run after connecting.";
        english["UiText.031"] = "Example: cd /var/log";
        english["UiText.032"] = "Protocol Version Priority";
        english["UiText.033"] = "Select the preferred SSH version. Usually SSH2 provides higher security and more features.";
        english["UiText.034"] = "Xagent (SSH Authentication Agent)";
        english["UiText.035"] = "Xagent remembers passwords and passes them to the server when requested.";
        english["UiText.036"] = "Use SSH key agent (Xagent) (U)";
        english["UiText.037"] = "Allow agent forwarding (E)";
        english["UiText.038"] = "Other";
        english["UiText.039"] = "Use ZLIB compression (Z)";
        english["UiText.040"] = "Do not allocate a terminal (D)";
        english["UiText.041"] = "Automatically accept and save host key on first connection (A)";
        english["UiText.042"] = "Open SFTP panel after SSH connection (S)";
        english["UiText.043"] = "Algorithms";
        english["UiText.044"] = "Select algorithms for SSH connections. Choose &lt;... List&gt; to use the default or edited algorithm list.";
        english["UiText.045"] = "Encryption (E):";
        english["UiText.046"] = "Edit (D)...";
        english["UiText.047"] = "Edit (I)...";
        english["UiText.048"] = "Key Exchange (K):";
        english["UiText.049"] = "Edit (T)...";
        english["UiText.050"] = "TCP/IP Forwarding";
        english["UiText.051"] = "Add, edit, or delete TCP/IP forwarding rules. These rules are applied automatically after connection.";
        english["UiText.052"] = "Type";
        english["UiText.053"] = "Listen Port";
        english["UiText.054"] = "Target";
        english["UiText.055"] = "Description";
        english["UiText.056"] = "X11 Forwarding";
        english["UiText.057"] = "Forward X11 connections to (X):";
        english["UiText.058"] = "When using an X server, specify the DISPLAY address, display number, and screen number.";
        english["UiText.059"] = "Use XDISPLOC Telnet option";
        english["UiText.060"] = "Display";
        english["UiText.061"] = "Note: PCADDR is replaced by the local IP address used by the current connection.";
        english["UiText.062"] = "Option Negotiation";
        english["UiText.063"] = "Select the TELNET option negotiation mode:";
        english["UiText.064"] = "Options";
        english["UiText.065"] = "Force character-at-a-time mode";
        english["UiText.066"] = "Proxy Server";
        english["UiText.067"] = "If your network uses a proxy server or firewall, select a suitable proxy server below. Click Browse to add, edit, or delete proxy servers.";
        english["UiText.068"] = "Proxy server (R):";
        english["UiText.069"] = "Browse (B)...";
        english["UiText.070"] = "Terminal speed (T):";
        english["UiText.071"] = "Startup Folders";
        english["UiText.072"] = "Specify the local and remote folders to go to automatically after connecting.";
        english["UiText.073"] = "Local folder (L):";
        english["UiText.074"] = "Select the default upload and download directory";
        english["UiText.075"] = "Remote folder (R):";
        english["UiText.076"] = "SFTP Server";
        english["UiText.077"] = "Use custom SFTP server (S)";
        english["UiText.078"] = "Command (C):";
        english["UiText.079"] = "By default, the SSH standard SFTP subsystem is used. Custom commands are saved to the session configuration and require lower-level channel support when connecting.";
        english["UiText.080"] = "General";
        english["UiText.081"] = "Port number (P):";
        english["UiText.082"] = "Baud rate (B):";
        english["UiText.083"] = "Data bits (D):";
        english["UiText.084"] = "Stop bits (S):";
        english["UiText.085"] = "Parity (A):";
        english["UiText.086"] = "Flow control (F):";
        english["UiText.087"] = "Window size (W):";
        english["UiText.088"] = "Resize screen (C):";
        english["UiText.089"] = "Color quality (Q):";
        english["UiText.090"] = "Devices";
        english["UiText.091"] = "Apply key combinations on the remote computer";
        english["UiText.092"] = "Share this computer's drives with the remote computer";
        english["UiText.093"] = "Sound";
        english["UiText.094"] = "Remote audio playback";
        english["UiText.095"] = "Record from this computer";
        english["UiText.096"] = "Emulation";
        english["UiText.097"] = "Terminal type (T):";
        english["UiText.098"] = "Columns (O):";
        english["UiText.099"] = "Rows (R):";
        english["UiText.100"] = "Fixed terminal size (F)";
        english["UiText.101"] = "Reset terminal size on connect (C)";
        english["UiText.102"] = "Scrollback Buffer";
        english["UiText.103"] = "Buffer size (S):";
        english["UiText.104"] = "Lines";
        english["UiText.105"] = "Push cleared screen to scrollback buffer (P)";
        english["UiText.106"] = "Conversion";
        english["UiText.107"] = "Encoding (E):";
        english["UiText.108"] = "Ambiguous-width characters (A):";
        english["UiText.109"] = "Treat ambiguous-width characters as wide";
        english["UiText.110"] = "Line Endings";
        english["UiText.111"] = "Send (D):";
        english["UiText.112"] = "Receive (V):";
        english["UiText.113"] = "Preview:";
        english["UiText.114"] = "Text color  Use bold color and font";
        english["UiText.115"] = "Color scheme (O):";
        english["UiText.116"] = "Font";
        english["UiText.117"] = "Font (F):";
        english["UiText.118"] = "Asian font (S):";
        english["UiText.119"] = "Use variable pitch font (V)";
        english["UiText.120"] = "Font quality (Q):";
        english["UiText.121"] = "Bold text (B):";
        english["UiText.122"] = "Cursor";
        english["UiText.123"] = "Cursor color (R):";
        english["UiText.124"] = "Use blinking cursor (U)";
        english["UiText.125"] = "Text color (T):";
        english["UiText.126"] = "Speed (P):";
        english["UiText.127"] = "Shape (A):";
        english["UiText.128"] = "Block";
        english["UiText.129"] = "Vertical bar";
        english["UiText.130"] = "Underline";
        english["UiText.131"] = "Margins";
        english["UiText.132"] = "Top (T):";
        english["UiText.133"] = "Bottom (B):";
        english["UiText.134"] = "Left (L):";
        english["UiText.135"] = "Right (R):";
        english["UiText.136"] = "Spacing";
        english["UiText.137"] = "Line spacing (I):";
        english["UiText.138"] = "Character spacing (H):";
        english["UiText.139"] = "Tab color";
        english["UiText.140"] = "Default";
        english["UiText.141"] = "Red";
        english["UiText.142"] = "Purple";
        english["UiText.143"] = "Yellow";
        english["UiText.144"] = "Other:";
        english["UiText.145"] = "Background Image";
        english["UiText.146"] = "File (F):";
        english["UiText.147"] = "Position (P):";
        english["UiText.148"] = "Highlight";
        english["UiText.149"] = "Highlight sets let you configure keywords highlighted in the CxShell terminal. These keywords also support regular expressions.";
        english["UiText.150"] = "Highlight Set";
        english["UiText.151"] = "Function Key Emulation";
        english["UiText.152"] = "Function key type (T):";
        english["UiText.153"] = "Note: when &lt;Default&gt; is selected, CxShell automatically chooses suitable function keys based on the terminal type.";
        english["UiText.154"] = "Specify the key mapping file to replace (S):";
        english["UiText.155"] = "DELETE key sequence";
        english["UiText.156"] = "BACKSPACE key sequence";
        english["UiText.157"] = "Meta Key Emulation";
        english["UiText.158"] = "The following options are needed when terminal applications such as Emacs require Meta keys.";
        english["UiText.159"] = "Use left ALT as Meta key (U)";
        english["UiText.160"] = "Use Ctrl+Alt as Alt Gr (G)";
        english["UiText.161"] = "Use right ALT as Meta key (R)";
        english["UiText.162"] = "Initial VT Mode";
        english["UiText.163"] = "Initial cursor key mode (DECCKM):";
        english["UiText.164"] = "Normal (M)";
        english["UiText.165"] = "Application (P)";
        english["UiText.166"] = "Initial numeric keypad mode (DECNKM):";
        english["UiText.167"] = "Normal (L)";
        english["UiText.168"] = "Application (I)";
        english["UiText.169"] = "Set to normal (S)";
        english["UiText.170"] = "Use application mouse mode (U)";
        english["UiText.171"] = "Limit application mouse mode when SHIFT is pressed (S)";
        english["UiText.172"] = "Clear screen background color (E)";
        english["UiText.173"] = "Scroll to bottom on terminal input/output (B)";
        english["UiText.174"] = "Suspend scroll-to-bottom while Scroll Lock is active (L)";
        english["UiText.175"] = "Scroll to bottom by key (O)";
        english["UiText.176"] = "Enable destructive BACKSPACE (N)";
        english["UiText.177"] = "Move to working directory after duplicating session (M)";
        english["UiText.178"] = "Expected string (X):";
        english["UiText.179"] = "Leave empty to run cd immediately";
        english["UiText.180"] = "Use rxvt Home/End keys (R)";
        english["UiText.181"] = "Miscellaneous";
        english["UiText.182"] = "Disable blinking text (D)";
        english["UiText.183"] = "Disable terminal title changes (I)";
        english["UiText.184"] = "Disable terminal printing (A)";
        english["UiText.185"] = "Disable alternate screen switching (T)";
        english["UiText.186"] = "Ignore terminal resize requests (Q)";
        english["UiText.187"] = "Answerback to ^E (W):";
        english["UiText.188"] = "Font Options";
        english["UiText.189"] = "Use built-in line drawing characters (H)";
        english["UiText.190"] = "Use built-in font for Powerline support (P)";
        english["UiText.191"] = "Receive Folder";
        english["UiText.192"] = "Specify the folder for saving received files.";
        english["UiText.193"] = "Always ask before downloading (L)";
        english["UiText.194"] = "Use the following download path (D):";
        english["UiText.195"] = "Download path (W):";
        english["UiText.196"] = "Open (O)";
        english["UiText.197"] = "Upload path (U):";
        english["UiText.198"] = "Open (P)";
        english["UiText.199"] = "Duplicate File Handling";
        english["UiText.200"] = "Choose what to do when a file with the same name exists.";
        english["UiText.201"] = "Auto rename (R)";
        english["UiText.202"] = "Overwrite (V)";
        english["UiText.203"] = "Upload Protocol";
        english["UiText.204"] = "Specify the upload protocol to use when you drag and drop files into CxShell.";
        english["UiText.205"] = "Zmodem (default)";
        english["UiText.206"] = "Select the block size.";
        english["UiText.207"] = "Upload Command";
        english["UiText.208"] = "Set the command used to upload files with X/YMODEM. The file name is automatically appended to the end of the command.";
        english["UiText.209"] = "Xmodem command (X):";
        english["UiText.210"] = "Ymodem command (Y):";
        english["UiText.211"] = "Select the next option so CxShell detects ZMODEM transfer status on the remote host and starts automatic file transfer.";
        english["UiText.212"] = "Auto-activate ZMODEM (A)";
        english["UiText.213"] = "Set the command used to upload files with ZMODEM. The file name is automatically appended to the end of the command.";
        english["UiText.214"] = "Zmodem command (Z):";
        english["UiText.215"] = "Log File";
        english["UiText.216"] = "File path (F):";
        english["UiText.217"] = "Overwrite if file exists (O)";
        english["UiText.218"] = "Start logging on connect (C)";
        english["UiText.219"] = "Choose a file path when logging starts (P)";
        english["UiText.220"] = "Apply RTF format (R)";
        english["UiText.221"] = "Include terminal codes (T)";
        english["UiText.222"] = "Timestamp";
        english["UiText.223"] = "Write to log file (W)";
        english["UiText.224"] = "Format (M):";
        english["UiText.225"] = "Preview (V):";
        english["UiText.226"] = "%n: session name, %u: username, %{HN}: host name, %{hn}: short host name&#x0a;%Y: year, %m: month, %d: day, %t: time, %h: hour, %M: minute, %s: second, %N: millisecond&#x0a;%a: locale, %l: line number";
        english["UiText.227"] = "None (ignore bell requests) (N)";
        english["UiText.228"] = "Default sound (D)";
        english["UiText.229"] = "Built-in speaker (S)";
        english["UiText.230"] = "Play specified sound (P):";
        english["UiText.231"] = "Flash window and taskbar when focus is not on a window (F)";
        english["UiText.232"] = "Ignore repeated bells";
        english["UiText.233"] = "Temporarily disable bell if requested multiple times within (T):";
        english["UiText.234"] = "seconds";
        english["UiText.235"] = "Re-enable after the next period (E):";
        english["UiText.236"] = "Quick Command Set";
        english["UiText.237"] = "Disable quick command shortcut keys (D)";
        english["UiText.238"] = "ftp Options";
        english["UiText.239"] = "Use the following FTP port when invoking ftp (F):";
        english["UiText.240"] = "Reset (R)";
        english["UiText.241"] = "Delayed Send";
        english["UiText.242"] = "Set the delay interval between characters.";
        english["UiText.243"] = "Character delay (C):";
        english["UiText.244"] = "millisec";
        english["UiText.245"] = "Set the delay interval between lines.";
        english["UiText.246"] = "Line delay (L):";
        english["UiText.247"] = "Prompt (P)";
        english["UiText.248"] = "Max wait (ms) (M):";
        english["UiText.249"] = "TCP Options";
        english["UiText.250"] = "Use Nagle algorithm (U)";
        english["UiText.251"] = "Internet Protocol Version";
        english["UiText.252"] = "Auto (I)";
        english["UiText.253"] = "Select events to trace. Selected event status is output to the terminal window.";
        english["UiText.254"] = "Protocol Events";
        english["UiText.255"] = "SSH version, algorithm exchange, and user authentication (S)";
        english["UiText.256"] = "SSH TCP/IP and X11 tunneling (H)";
        english["UiText.257"] = "SSH packets (P)";
        english["UiText.258"] = "TELNET option mode (T)";
        english["UiText.259"] = "Send Clipboard";
        english["UiText.260"] = "Open monitor panel after SSH connection (M)";
        english["UiText.261"] = "Follow terminal current directory (F)";

        chinese["UiText.001"] = "服务器监控";
        chinese["UiText.002"] = "内存";
        chinese["UiText.003"] = "网络";
        chinese["UiText.004"] = "↓ 下载";
        chinese["UiText.005"] = "↑ 上传";
        chinese["UiText.006"] = "磁盘";
        chinese["UiText.007"] = "磁盘 I/O";
        chinese["UiText.008"] = "读";
        chinese["UiText.009"] = "写";
        chinese["UiText.010"] = "保持活动状态";
        chinese["UiText.011"] = "连接会话期间发送保持活动状态消息(S)";
        chinese["UiText.012"] = "间隔(I):";
        chinese["UiText.013"] = "网络空闲时发送字符串(R)";
        chinese["UiText.014"] = "间隔(E):";
        chinese["UiText.015"] = "字符串(G):";
        chinese["UiText.016"] = "网络为空闲状态时发送 TCP 保持活动数据包(T)";
        chinese["UiText.017"] = "用户名提示";
        chinese["UiText.018"] = "密码提示";
        chinese["UiText.019"] = "请指定密码提示，以便 RLOGIN 登录过程可自动运行。";
        chinese["UiText.020"] = "成功登录服务器后，可以执行使用等待并发送规则添加的命令或者使用第二次自动登录。";
        chinese["UiText.021"] = "执行以下等待并发送规则(X).";
        chinese["UiText.022"] = "添加(A)...";
        chinese["UiText.023"] = "编辑(E)...";
        chinese["UiText.024"] = "删除(R)";
        chinese["UiText.025"] = "上移(U)";
        chinese["UiText.026"] = "下移(D)";
        chinese["UiText.027"] = "连接会话时运行脚本(S).";
        chinese["UiText.028"] = "参数(P):";
        chinese["UiText.029"] = "远程命令";
        chinese["UiText.030"] = "指定连接后要运行的远程命令。";
        chinese["UiText.031"] = "例如：cd /var/log";
        chinese["UiText.032"] = "协议版本优先级";
        chinese["UiText.033"] = "选择首选的 SSH 版本。通常，SSH2 提供高安全性和更多的特征。";
        chinese["UiText.034"] = "Xagent (SSH 身份验证代理)";
        chinese["UiText.035"] = "Xagent 会记住密码，并在请求时将其传递给服务器。";
        chinese["UiText.036"] = "使用 SSH 密钥代理(Xagent)(U)";
        chinese["UiText.037"] = "允许代理转发(E)";
        chinese["UiText.038"] = "其他";
        chinese["UiText.039"] = "使用 ZLIB 压缩(Z)";
        chinese["UiText.040"] = "不分配终端(D)";
        chinese["UiText.041"] = "第一次连接时自动接受并保存主机密钥(A)";
        chinese["UiText.042"] = "连接 SSH 后自动打开 SFTP 面板(S)";
        chinese["UiText.043"] = "算法";
        chinese["UiText.044"] = "选择要使用的算法 SSH 连接。选择 &lt;... List&gt; 使用默认或编辑后的算法列表。";
        chinese["UiText.045"] = "加密(E):";
        chinese["UiText.046"] = "编辑(D)...";
        chinese["UiText.047"] = "编辑(I)...";
        chinese["UiText.048"] = "密钥交换(K):";
        chinese["UiText.049"] = "编辑(T)...";
        chinese["UiText.050"] = "TCP/IP 转移";
        chinese["UiText.051"] = "添加/编辑/删除 TCP/IP 转移规则。此规则连接后自动应用。";
        chinese["UiText.052"] = "类型";
        chinese["UiText.053"] = "侦听端口";
        chinese["UiText.054"] = "目标";
        chinese["UiText.055"] = "说明";
        chinese["UiText.056"] = "X11 转移";
        chinese["UiText.057"] = "转发 X11 连接到(X):";
        chinese["UiText.058"] = "使用 X 服务器时，可指定 DISPLAY 地址、显示编号和屏幕编号。";
        chinese["UiText.059"] = "使用 XDISPLOC Telnet 选项";
        chinese["UiText.060"] = "显示";
        chinese["UiText.061"] = "注释：PCADDR 会替换为当前连接使用的本机 IP 地址。";
        chinese["UiText.062"] = "选项协商";
        chinese["UiText.063"] = "请选择 TELNET 选项协商模式：";
        chinese["UiText.064"] = "选项";
        chinese["UiText.065"] = "强制 Character-at-a-time 模式";
        chinese["UiText.066"] = "代理服务器";
        chinese["UiText.067"] = "用户的网络环境使用代理服务器防火墙时，请在下方选择合适的代理服务器。要添加、编辑或删除代理服务器，请点击“浏览”。";
        chinese["UiText.068"] = "代理服务器(R):";
        chinese["UiText.069"] = "浏览(B)...";
        chinese["UiText.070"] = "终端速度(T):";
        chinese["UiText.071"] = "启动文件夹";
        chinese["UiText.072"] = "连接后自动指定转到的本地文件夹和远程文件夹。";
        chinese["UiText.073"] = "本地文件夹(L):";
        chinese["UiText.074"] = "选择上传和下载默认目录";
        chinese["UiText.075"] = "远程文件夹(R):";
        chinese["UiText.076"] = "SFTP服务器";
        chinese["UiText.077"] = "使用自定义SFTP服务器(S)";
        chinese["UiText.078"] = "命令(C):";
        chinese["UiText.079"] = "默认使用 SSH 标准 sftp subsystem；自定义命令保存到会话配置，当前连接时会提示需要低层通道支持。";
        chinese["UiText.080"] = "常规";
        chinese["UiText.081"] = "端口号(P):";
        chinese["UiText.082"] = "波特率(B):";
        chinese["UiText.083"] = "数据位(D):";
        chinese["UiText.084"] = "停止位(S):";
        chinese["UiText.085"] = "奇偶校验(A):";
        chinese["UiText.086"] = "流控制(F):";
        chinese["UiText.087"] = "窗口大小(W):";
        chinese["UiText.088"] = "改变屏幕大小(C):";
        chinese["UiText.089"] = "颜色质量(Q):";
        chinese["UiText.090"] = "设备";
        chinese["UiText.091"] = "在远程计算机上应用密钥组合";
        chinese["UiText.092"] = "与远程计算机分享该计算机的驱动器";
        chinese["UiText.093"] = "声音";
        chinese["UiText.094"] = "远程音频播放";
        chinese["UiText.095"] = "从这台电脑录制";
        chinese["UiText.096"] = "仿真";
        chinese["UiText.097"] = "终端类型(T):";
        chinese["UiText.098"] = "列(O):";
        chinese["UiText.099"] = "行(R):";
        chinese["UiText.100"] = "固定终端大小(F)";
        chinese["UiText.101"] = "连接时重置端子尺寸(C)";
        chinese["UiText.102"] = "滚动缓冲区";
        chinese["UiText.103"] = "缓冲区大小(S):";
        chinese["UiText.104"] = "行";
        chinese["UiText.105"] = "将清除的屏幕推到滚动缓冲区(P)";
        chinese["UiText.106"] = "转换";
        chinese["UiText.107"] = "编码(E):";
        chinese["UiText.108"] = "模糊宽度字符(A):";
        chinese["UiText.109"] = "将含糊的大小字符视为宽字符";
        chinese["UiText.110"] = "换行符";
        chinese["UiText.111"] = "发送(D):";
        chinese["UiText.112"] = "收到(V):";
        chinese["UiText.113"] = "预览:";
        chinese["UiText.114"] = "文本颜色  使用大胆的颜色和字体";
        chinese["UiText.115"] = "配色方案(O):";
        chinese["UiText.116"] = "字体";
        chinese["UiText.117"] = "字体(F):";
        chinese["UiText.118"] = "亚洲字体(S):";
        chinese["UiText.119"] = "使用可变间距字体(V)";
        chinese["UiText.120"] = "字体质量(Q):";
        chinese["UiText.121"] = "“加粗”文本(B):";
        chinese["UiText.122"] = "游标";
        chinese["UiText.123"] = "游标颜色(R):";
        chinese["UiText.124"] = "使用闪烁的光标(U)";
        chinese["UiText.125"] = "文本颜色(T):";
        chinese["UiText.126"] = "速度(P):";
        chinese["UiText.127"] = "外观(A):";
        chinese["UiText.128"] = "块";
        chinese["UiText.129"] = "竖线";
        chinese["UiText.130"] = "下划线";
        chinese["UiText.131"] = "边距";
        chinese["UiText.132"] = "顶(T):";
        chinese["UiText.133"] = "底部(B):";
        chinese["UiText.134"] = "左(L):";
        chinese["UiText.135"] = "右(R):";
        chinese["UiText.136"] = "间隔";
        chinese["UiText.137"] = "行距(I):";
        chinese["UiText.138"] = "字符间距(H):";
        chinese["UiText.139"] = "工作表标签颜色";
        chinese["UiText.140"] = "默认";
        chinese["UiText.141"] = "红";
        chinese["UiText.142"] = "紫色";
        chinese["UiText.143"] = "黄色";
        chinese["UiText.144"] = "其他:";
        chinese["UiText.145"] = "背景图";
        chinese["UiText.146"] = "文件(F):";
        chinese["UiText.147"] = "位置(P):";
        chinese["UiText.148"] = "突出显示";
        chinese["UiText.149"] = "突出显示集允许您配置在 CxShell 终端上突出显示的关键字列表。这些关键字也支持正则表达式。";
        chinese["UiText.150"] = "高亮集";
        chinese["UiText.151"] = "功能键仿真";
        chinese["UiText.152"] = "功能键类型(T):";
        chinese["UiText.153"] = "注释: 选择&lt;默认&gt;时，CxShell 根据终端类型自动选择恰当的功能键。";
        chinese["UiText.154"] = "请指定要替换的按键对应文件(S):";
        chinese["UiText.155"] = "DELETE 键序列";
        chinese["UiText.156"] = "BACKSPACE 键序列";
        chinese["UiText.157"] = "元(Meta)键仿真";
        chinese["UiText.158"] = "终端作业时使用需要如 Emacs 等相关的 Meta 键的应用程序时，需要以下选项。";
        chinese["UiText.159"] = "将左 ALT 用作 Meta 键(U)";
        chinese["UiText.160"] = "将 Ctrl+Alt 用作 Alt Gr(G)";
        chinese["UiText.161"] = "将右 ALT 用作 Meta 键(R)";
        chinese["UiText.162"] = "初始VT模式";
        chinese["UiText.163"] = "初始光标键模式 (DECCKM):";
        chinese["UiText.164"] = "普通(M)";
        chinese["UiText.165"] = "应用程序(P)";
        chinese["UiText.166"] = "初始数字键盘模式 (DECNKM):";
        chinese["UiText.167"] = "普通(L)";
        chinese["UiText.168"] = "应用程序(I)";
        chinese["UiText.169"] = "设置为普通(S)";
        chinese["UiText.170"] = "使用应用程序鼠标模式(U)";
        chinese["UiText.171"] = "按下 SHIFT 键时限制应用程序鼠标模式(S)";
        chinese["UiText.172"] = "清除屏幕背景颜色(E)";
        chinese["UiText.173"] = "输入/输出终端时滚动到底部(B)";
        chinese["UiText.174"] = "激活滚动锁定时，暂停终端滚动到底部功能(L)";
        chinese["UiText.175"] = "按键滚动到底部(O)";
        chinese["UiText.176"] = "启用破坏性 BACKSPACE(N)";
        chinese["UiText.177"] = "会话复制后移至工作目录(M)";
        chinese["UiText.178"] = "预期字符串(X):";
        chinese["UiText.179"] = "留空立即运行 cd";
        chinese["UiText.180"] = "使用 rxvt 作为 Home/End 键(R)";
        chinese["UiText.181"] = "杂项";
        chinese["UiText.182"] = "禁用闪烁文本(D)";
        chinese["UiText.183"] = "禁用更改终端标题(I)";
        chinese["UiText.184"] = "禁用终端打印功能(A)";
        chinese["UiText.185"] = "禁用终端替换屏幕（Alternate Screen）切换(T)";
        chinese["UiText.186"] = "忽略终端大小变更申请(Q)";
        chinese["UiText.187"] = "应答到 ^E(W):";
        chinese["UiText.188"] = "字体选项";
        chinese["UiText.189"] = "使用内置的字体画线字符(H)";
        chinese["UiText.190"] = "使用内置的字体，以支持 Powerline(P)";
        chinese["UiText.191"] = "接收文件夹";
        chinese["UiText.192"] = "指定保存接收文件的文件夹。";
        chinese["UiText.193"] = "下载前始终询问(L)";
        chinese["UiText.194"] = "使用下列下载路径(D):";
        chinese["UiText.195"] = "下载路径(W):";
        chinese["UiText.196"] = "打开(O)";
        chinese["UiText.197"] = "加载路径(U):";
        chinese["UiText.198"] = "打开(P)";
        chinese["UiText.199"] = "重复的文件处理";
        chinese["UiText.200"] = "当存在具有相同名称的文件时，选择要执行的操作。";
        chinese["UiText.201"] = "自动重命名(R)";
        chinese["UiText.202"] = "覆盖(V)";
        chinese["UiText.203"] = "上传协议";
        chinese["UiText.204"] = "指定文件上传协议来使用，当你拖放文件到 CxShell。";
        chinese["UiText.205"] = "Zmodem(默认)";
        chinese["UiText.206"] = "选择分组的大小。";
        chinese["UiText.207"] = "上传命令";
        chinese["UiText.208"] = "设置要用于与 X/YMODEM 上传文件的命令。（文件名会自动添加到该命令结束。）";
        chinese["UiText.209"] = "Xmodem命令(X):";
        chinese["UiText.210"] = "Ymodem命令(Y):";
        chinese["UiText.211"] = "选择下一个选项，CxShell 检测远程主机的 ZMODEM 文件转移状态并启动自动转移文件。";
        chinese["UiText.212"] = "自动激活ZMODEM(A)";
        chinese["UiText.213"] = "设置要用于与 ZMODEM 上传文件的命令。（文件名会自动添加到该命令结束。）";
        chinese["UiText.214"] = "Zmodem命令(Z):";
        chinese["UiText.215"] = "日志文件";
        chinese["UiText.216"] = "文件路径(F):";
        chinese["UiText.217"] = "文件已存在时覆盖(O)";
        chinese["UiText.218"] = "连接时开始日志记录(C)";
        chinese["UiText.219"] = "开始记录时，选择一个文件路径(P)";
        chinese["UiText.220"] = "应用RTF格式(R)";
        chinese["UiText.221"] = "包括终端代码(T)";
        chinese["UiText.222"] = "时间戳";
        chinese["UiText.223"] = "写入日志文件(W)";
        chinese["UiText.224"] = "格式(M):";
        chinese["UiText.225"] = "预览(V):";
        chinese["UiText.226"] = "%n: 会话名称, %u: 用户名, %{HN}: 主机名, %{hn}: 短主机名&#x0a;%Y: 年, %m: 月, %d: 日, %t: 时间, %h: 时, %M: 分, %s: 秒, %N: 毫秒&#x0a;%a: 语言环境, %l: 行号";
        chinese["UiText.227"] = "无（忽略响铃请求）(N)";
        chinese["UiText.228"] = "默认提示音(D)";
        chinese["UiText.229"] = "内置蜂鸣器(S)";
        chinese["UiText.230"] = "播放指定声音(P):";
        chinese["UiText.231"] = "当焦点不在一个窗口上，闪烁的窗口和任务栏(F)";
        chinese["UiText.232"] = "忽略(重复)响铃";
        chinese["UiText.233"] = "如果在以下时间内多次请求铃声，则暂时禁用铃声(T):";
        chinese["UiText.234"] = "秒";
        chinese["UiText.235"] = "在下一段时间后重新启用它(E):";
        chinese["UiText.236"] = "快速命令集";
        chinese["UiText.237"] = "禁用快速命令快捷方式键(D)";
        chinese["UiText.238"] = "ftp选项";
        chinese["UiText.239"] = "调用ftp时，请使用以下FTP端口(F):";
        chinese["UiText.240"] = "重置(R)";
        chinese["UiText.241"] = "延迟发送";
        chinese["UiText.242"] = "设置字符之间的延迟时间间隔。";
        chinese["UiText.243"] = "字符延迟(C):";
        chinese["UiText.244"] = "毫秒";
        chinese["UiText.245"] = "设置行之间的延迟时间间隔。";
        chinese["UiText.246"] = "线路延迟(L):";
        chinese["UiText.247"] = "提示(P)";
        chinese["UiText.248"] = "最大等待(ms)(M):";
        chinese["UiText.249"] = "TCP选项";
        chinese["UiText.250"] = "使用Nagle算法(U)";
        chinese["UiText.251"] = "互联网协议版本";
        chinese["UiText.252"] = "自动(I)";
        chinese["UiText.253"] = "选择跟踪的事件。所选的事件状态将输出到终端窗口中。";
        chinese["UiText.254"] = "协议事件";
        chinese["UiText.255"] = "SSH版本、算法交换和用户身份验证(S)";
        chinese["UiText.256"] = "SSH TCP/IP 和 X11隧道(H)";
        chinese["UiText.257"] = "SSH数据包(P)";
        chinese["UiText.258"] = "TELNET选项模式(T)";
        chinese["UiText.259"] = "发送剪贴板";
        chinese["UiText.260"] = "连接 SSH 后自动打开监控面板(M)";
        chinese["UiText.261"] = "跟随终端当前目录(F)";
    }

    public string Language { get; private set; } = Chinese;
    public bool IsEnglish => string.Equals(Language, English, StringComparison.OrdinalIgnoreCase);
    public event EventHandler? LanguageChanged;
    public event PropertyChangedEventHandler? PropertyChanged;

    public string this[string key] => Text(key);

    public void SetLanguage(string? language)
    {
        var newLanguage = string.Equals(language, English, StringComparison.OrdinalIgnoreCase)
            ? English
            : Chinese;
        if (string.Equals(Language, newLanguage, StringComparison.OrdinalIgnoreCase))
            return;

        Language = newLanguage;
        OnPropertyChanged("Item[]");
        OnPropertyChanged(nameof(Language));
        OnPropertyChanged(nameof(IsEnglish));
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    public string Text(string key)
    {
        var source = IsEnglish ? EnglishTexts : ChineseTexts;
        return source.TryGetValue(key, out var value) ? value : key;
    }

    private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
